version: '3'
services:
  db:
    image: postgis/postgis:15-3.3
    container_name: redsidewalk-db
    environment:
      POSTGRES_USER: redsidewalk_user       # PostgreSQL username
      POSTGRES_PASSWORD: securepassword     # PostgreSQL password
      POSTGRES_DB: redsidewalk              # PostgreSQL database name
    ports:
      - "5432:5432"                         # Exposes port 5432 for local access
    volumes:
      - ./db:/docker-entrypoint-initdb.d 
      # Initializes DB with dump
      - postgres_data:/var/lib/postgresql/data
      # persistent volume after container stops


  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./cryptid-sightings
    container_name: frontend
    ports:
      - "3000:3000"  # Next.js dev server
    volumes:
      - ./cryptid-sightings:/app  # Watch local files for hot reload
      - /app/node_modules # Avoid overwriting node_modules
    command: sh -c "npm run build && npm run start"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:3000 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

volumes:
  postgres_data:


